//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphs
    {
        public int graphCode { get; set; }
        public string graphString { get; set; }
        public int userCode { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
